# --- Redis (轻量级队列) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine # Alpine 镜像在 ARM 上非常小
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "64Mi"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis

---
# --- MinIO (对象存储 - 运行在挂载了 SSD 的树莓派上) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      # 关键点：强制调度到存储节点
      nodeSelector:
        device: storage
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z # 这里的版本号建议固定
        args:
        - server
        - /data
        - --console-address
        - :9001
        env:
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "password123" # 请修改为强密码
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        hostPath:
          # 这里填写你树莓派上 SSD 挂载的真实路径
          path: /mnt/ssd/minio_data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - port: 9000
      name: api
    - port: 9001
      name: console
  selector:
    app: minio