# --- ASR Engine (运行在 Jetson 上) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr-engine
  template:
    metadata:
      labels:
        app: asr-engine
    spec:
      # 关键点：强制调度到 Jetson GPU 节点
      nodeSelector:
        device: gpu
      # 必须指定 runtime class 才能在 K3s 中使用 GPU
      runtimeClassName: nvidia 
      containers:
      - name: engine
        # 假设你有一个封装了 Faster-Whisper 或 Kaldi 的镜像
        image: my-asr-engine:gpu-v1 
        resources:
          limits:
            nvidia.com/gpu: 1 # 请求 1 个 GPU
          requests:
            memory: "2Gi"
            cpu: "1000m"

---
# --- Session Logger API (运行在任意节点，负责接收请求) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-logger
spec:
  replicas: 2 # 可以多开几个副本实现高可用
  selector:
    matchLabels:
      app: session-logger
  template:
    metadata:
      labels:
        app: session-logger
    spec:
      containers:
      - name: api
        image: my-asr-logger:v1 # 刚才构建的镜像
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: MINIO_ENDPOINT
          value: "minio:9000"
        - name: AWS_ACCESS_KEY_ID
          value: "admin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "password123"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: session-logger
spec:
  type: LoadBalancer # K3s 自带 ServiceLB，可以直接暴露 IP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: session-logger