
# --- NATS StatefulSet (带存储的有状态应用) ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  serviceName: "nats"
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      # 建议调度到有 SSD 的节点，保证队列读写极快
      nodeSelector:
        device: storage
      containers:
      - name: nats
        image: nats:2.10-alpine # 官方镜像支持 ARM64
        args: ["-js", "-m", "8222"] # -js 开启 JetStream, -m 开启监控端口
        ports:
        - containerPort: 4222 # 客户端连接端口
        - containerPort: 8222 # 监控面板 http://<ip>:8222
        volumeMounts:
        - name: nats-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: nats-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  ports:
  - port: 4222
    name: client
  - port: 8222
    name: monitor
  selector:
    app: nats